plugins {
	id 'java'
	id 'org.springframework.boot' version '3.5.4' apply false
	id 'io.spring.dependency-management' version '1.1.7' apply false
}

def springBootVersion = '3.5.4'
def lombokVersion = '1.18.30'

group = 'com.vitalitsoft'
version = '1.0.0'
description = 'Servicio de autenticación'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(17)
	}
}

subprojects {
	apply plugin: 'java'
	apply plugin: 'io.spring.dependency-management'

	repositories {
		mavenCentral()
	}

	dependencies {
		implementation platform("org.springframework.boot:spring-boot-dependencies:${springBootVersion}")
		implementation 'io.projectreactor:reactor-core'
		implementation 'io.projectreactor.addons:reactor-extra'
		implementation 'org.reactivecommons.utils:object-mapper:0.1.0'
		testImplementation 'io.projectreactor.tools:blockhound-junit-platform:1.0.13.RELEASE'
		testImplementation 'io.projectreactor:reactor-test'
		testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
		testImplementation 'org.springframework.boot:spring-boot-starter-test'
		testImplementation 'com.fasterxml.jackson.core:jackson-databind'
		compileOnly "org.projectlombok:lombok:${lombokVersion}"
		annotationProcessor  "org.projectlombok:lombok:${lombokVersion}"
		testCompileOnly  "org.projectlombok:lombok:${lombokVersion}"
		testAnnotationProcessor  "org.projectlombok:lombok:${lombokVersion}"

	}
}