services:
  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_DB: ${R2DBC_DATABASE}
      POSTGRES_USER: ${R2DBC_USERNAME}
      POSTGRES_PASSWORD: ${R2DBC_PASSWORD}
    ports:
      - "${R2DBC_PORT}:5432"
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/postgresql/data
  auth-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vitalitsoft-auth-service
    depends_on:
      - db
    ports:
      - "${SERVER_PORT}:8080"
    env_file:
      - .env
    environment:
      SPRING_PROFILES_ACTIVE: dev
    restart: unless-stopped

volumes:
  db_data:
