services:
  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_DB: ${R2DBC_DATABASE}
      POSTGRES_USER: ${R2DBC_USERNAME}
      POSTGRES_PASSWORD: ${R2DBC_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vitalitsoft-auth-service
    depends_on:
      - db
    ports:
      - "8081:8081"
    env_file:
      - .env
    environment:
      SPRING_PROFILES_ACTIVE: dev
    restart: unless-stopped

volumes:
  db_data:
